apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: basic-node
  description: Add basic-node to IDP

spec:
  type: service
  lifecycle: production
  owner: manisha.sahasrabudhe@harness.io
